apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: devops-microservice
  labels:
    app: springboot-mongodb-app
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: devops-microservice
  name: app-role
  labels:
    app: springboot-mongodb-app
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "configmaps"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: app-rolebinding
  namespace: devops-microservice
  labels:
    app: springboot-mongodb-app
subjects:
- kind: ServiceAccount
  name: app-service-account
  namespace: devops-microservice
roleRef:
  kind: Role
  name: app-role
  apiGroup: rbac.authorization.k8s.io
---