apiVersion: v1
kind: Secret
metadata:
  name: app-secrets
  namespace: devops-microservice
  labels:
    app: springboot-mongodb-app
type: Opaque
data:
  # Base64 encoded values
  # echo -n "admin" | base64
  MONGO_USERNAME: YWRtaW4=
  # echo -n "password123" | base64  
  MONGO_PASSWORD: cGFzc3dvcmQxMjM=
---
apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secrets
  namespace: devops-microservice
  labels:
    app: mongodb
type: Opaque
data:
  # Base64 encoded values
  MONGO_INITDB_ROOT_USERNAME: YWRtaW4=
  MONGO_INITDB_ROOT_PASSWORD: cGFzc3dvcmQxMjM=
---