apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "springboot-mongodb-app.fullname" . }}-config
  labels:
    {{- include "springboot-mongodb-app.labels" . | nindent 4 }}
data:
  database: {{ .Values.config.database | quote }}
  log-level: {{ .Values.config.logLevel | quote }}