apiVersion: v1
kind: Secret
metadata:
  name: {{ include "springboot-mongodb-app.fullname" . }}-secrets
  labels:
    {{- include "springboot-mongodb-app.labels" . | nindent 4 }}
type: Opaque
data:
  mongo-username: {{ .Values.secrets.mongoUsername | b64enc | quote }}
  mongo-password: {{ .Values.secrets.mongoPassword | b64enc | quote }}